import asyncio
import glob
import json
import os
import pprint
import re
import sys
import time
import configparser
import platform
from pathlib import Path

# --- 配布版パス解決 ---
# yomi-KAI.py が lib/ の中にある場合（配布版）、
# カレントディレクトリをルート（起動.bat と同じ階層）に割り当てる
_script_dir = Path(__file__).resolve().parent
if _script_dir.name == "lib":
    os.chdir(_script_dir.parent)

# lib/packagesが存在する場合（配布版）、sys.pathに追加して優先的に読み込む
pkg_path = _script_dir / "packages"
if pkg_path.exists():
    sys.path.insert(0, str(pkg_path))

from voicevox_core.blocking import Onnxruntime, OpenJtalk, Synthesizer, VoiceModelFile
from collections import defaultdict, deque
from datetime import datetime
from logging import (DEBUG, INFO, ERROR, NOTSET, FileHandler, Formatter, StreamHandler, basicConfig, getLogger)
import discord
from discord.ext import commands
from google.cloud import texttospeech
from google.api_core.client_options import ClientOptions
from unicodedata import east_asian_width

# ディレクトリ作成
if not os.path.isdir("dict"): os.mkdir("dict")
if not os.path.isdir("log"):  os.mkdir("log")
if not os.path.isdir("temp"): os.mkdir("temp")

# ログの設定
format = "[%(asctime)s] %(name)s:%(lineno)s %(funcName)s [%(levelname)s]: %(message)s"

sh = StreamHandler()
sh.setLevel(INFO)
sh.setFormatter(Formatter(format))

fh = FileHandler(f"./log/{datetime.now():%Y-%m-%d_%H%M%S}.log", encoding="UTF-8")
fh.setLevel(DEBUG)
fh.setFormatter(Formatter(format))

basicConfig(level=NOTSET, handlers=[sh, fh])
logger = getLogger(__name__)

# voicevox_core 内部の動作に影響のない警告ログ（バージョン差異など）を抑制
getLogger("voicevox_core").setLevel(ERROR)

# 起動時に./temp内の*.wavをすべて削除
for filename in glob.glob("./temp/*.wav"):
    os.remove(filename)

# ログを50個残す
file_list = glob.glob("./log/*.log")
if len(file_list) > 50:
    for i in range(len(file_list) - 50):
        os.remove(file_list[i])

# config.iniの確認
try:
    config = configparser.ConfigParser()
    config.read("config.ini", encoding="UTF-8")
    DISCORD_TOKEN     = config["DEFAULT"]["DISCORD_TOKEN"]
    USE_GOOGLE_TTS    = config.getboolean("DEFAULT", "USE_GOOGLE_TTS", fallback=False)
    if USE_GOOGLE_TTS:
        GOOGLE_API_KEY = config["DEFAULT"]["GOOGLE_API_KEY"]
    PREFIX            = config["DEFAULT"]["PREFIX"]
    AFK_TIME          = int(config["DEFAULT"]["AFK_TIME"])
    SD_MSG            = config["DEFAULT"]["SD_MSG"]
except Exception:
    logger.exception("config.iniが見つかりません。設定項目が足りていない可能性があります。")
    sys.exit()

# 設定読み込み完了
# キュー
queue_dict = defaultdict(deque)
def enqueue(voice_client, guild, source, filename):
    queue = queue_dict[guild.id]
    queue.append((source, filename))
    if not voice_client.is_playing():
        play(voice_client, queue)

def play(voice_client, queue):
    if not queue or voice_client.is_playing():
        return
    source, filename = queue.popleft()

    def after_play(error):
        if error:
            logger.error(f"再生中にエラーが発生しました: {error}")
        # 再生が終わった音声ファイルを削除
        try:
            os.remove(filename)
        except OSError:
            pass
        play(voice_client, queue)

    voice_client.play(source, after=after_play)


# Google Text to Speechでの読み上げ
_google_tts_client = None
def get_google_tts_client():
    global _google_tts_client
    if _google_tts_client is None:
        client_options = ClientOptions(api_key=GOOGLE_API_KEY)
        _google_tts_client = texttospeech.TextToSpeechClient(client_options=client_options)
    return _google_tts_client

def synthesize_text(text, speaker, gen_time):
    """Synthesizes speech from the input string of text."""
    client = get_google_tts_client()
    input_text = texttospeech.SynthesisInput(text=text)
    # Note: the voice can also be specified by name.
    # Names of voices can be retrieved with client.list_voices().
    voice = texttospeech.VoiceSelectionParams(language_code="ja-JP", name=speaker)
    audio_config = texttospeech.AudioConfig(audio_encoding=texttospeech.AudioEncoding.LINEAR16) # WAVを指定
    response = client.synthesize_speech(request={"input": input_text, "voice": voice, "audio_config": audio_config})
    # The response's audio_content is binary.
    with open(f"./temp/{gen_time}.wav", "wb") as f:
        f.write(response.audio_content)
        logger.info(f"The audio file ({gen_time}.wav) was successfully generated by Google.")

# voicevoxでの読み上げ
voicevox_dir = Path("./lib/voicevox_core") if Path("./lib/voicevox_core").exists() else Path("./voicevox_core")

try:
    onnx = Onnxruntime.get()
    if onnx is None:
        os_name = platform.system()
        if os_name == "Windows":
            onnx_lib = "voicevox_onnxruntime.dll"
        elif os_name == "Darwin":
            onnx_lib_pattern = "libvoicevox_onnxruntime.dylib*"
            candidate = list((voicevox_dir / "onnxruntime/lib").glob(onnx_lib_pattern))
            onnx_lib = candidate[0].name if candidate else "libvoicevox_onnxruntime.dylib"
        else:
            onnx_lib_pattern = "libvoicevox_onnxruntime.so*"
            candidate = list((voicevox_dir / "onnxruntime/lib").glob(onnx_lib_pattern))
            onnx_lib = candidate[0].name if candidate else "libvoicevox_onnxruntime.so"
            
        Onnxruntime.load_once(filename=str(voicevox_dir / f"onnxruntime/lib/{onnx_lib}"))
        onnx = Onnxruntime.get()
        
    openjtalk = OpenJtalk(voicevox_dir / "dict/open_jtalk_dic_utf_8-1.11")
    core = Synthesizer(onnx, openjtalk)
    for vvm_path in (voicevox_dir / "models/vvms").glob("*.vvm"):
        model = VoiceModelFile.open(vvm_path)
        core.load_voice_model(model)
except Exception as e:
    logger.exception("VOICEVOXの初期化に失敗しました。`voicevox_core`フォルダ内にモデルや辞書データが正しく配置されているか確認してください。")
    sys.exit()
def voicevox_synthesize(text, speaker, gen_time):
    # VOICEVOX COREを使用
    wave_bytes = core.tts(text, style_id=speaker)
    with open(f"./temp/{gen_time}.wav", "wb") as f:
        f.write(wave_bytes)
    logger.info(f"The audio file ({gen_time}.wav) was successfully generated by VOICEVOX.")

# 話者名 -> 合成方法のディスパッチ
GOOGLE_VOICES = {"ja-JP-Wavenet-A", "ja-JP-Wavenet-D"}
VOICEVOX_STYLE_IDS = {"ずんだもん": 3, "春日部つむぎ": 8}

def synthesize(speaker, text, gen_time):
    """話者名に応じて適切なエンジンで音声を合成する（ブロッキング処理）。"""
    if speaker in GOOGLE_VOICES:
        synthesize_text(text, speaker, gen_time)
    else:
        # 未知の話者はデフォルトのVOICEVOX話者にフォールバック
        style_id = VOICEVOX_STYLE_IDS.get(speaker, 3)
        voicevox_synthesize(text, style_id, gen_time)


# 声の選択
class Dropdown(discord.ui.Select):
    def __init__(self, guild_id):
        self.guild_id = guild_id
        # Set the options that will be presented inside the dropdown
        options = []
        if USE_GOOGLE_TTS:
            options.append(discord.SelectOption(label='ja-JP-Wavenet-A', description='Google女声'))
            options.append(discord.SelectOption(label='ja-JP-Wavenet-D', description='Google男声'))

        options.append(discord.SelectOption(label='ずんだもん', description='VOICEVOX ずんだもん'))
        options.append(discord.SelectOption(label='春日部つむぎ', description='VOICEVOX 春日部つむぎ'))
        # The placeholder is what will be shown when no option is chosen
        # The min and max values indicate we can only pick one of the three options
        # The options parameter defines the dropdown options. We defined this above
        super().__init__(placeholder=f'初期設定は{get_speaker(guild_id)}です', min_values=1, max_values=1, options=options)

    async def callback(self, interaction: discord.Interaction):
        # Use the interaction object to send a response message containing
        # the user's favourite colour or choice. The self object refers to the
        # Select object, and the values attribute gets a list of the user's
        # selected options. We only want the first one.
        selected_speaker[self.guild_id] = self.values[0]
        await interaction.response.send_message(f'{self.values[0]}が選択されました')

class DropdownView(discord.ui.View):
    def __init__(self, guild_id):
        super().__init__()
        # Adds the dropdown to our view object.
        self.add_item(Dropdown(guild_id))

# initial setup
intents = discord.Intents.default()
intents.message_content = True
intents.members = True 
bot = commands.Bot(command_prefix=PREFIX, intents=intents, help_command=None)
connected_channel = {} # guild -> 読み上げ対象のテキストチャンネル
default_speaker = 'ja-JP-Wavenet-A' if USE_GOOGLE_TTS else 'ずんだもん' # 初期設定のスピーカー
selected_speaker = {} # guild.id -> 話者名（サーバーごとに保持）
afk_tasks = {} # guild.id -> AFK自動切断用のタイマータスク

def get_speaker(guild_id):
    return selected_speaker.get(guild_id, default_speaker)


# 接続時の処理
@bot.event
async def on_ready():
    logger.info(f"Launch complete! Logged in as [{bot.user.name}]. PREFIX is [{PREFIX}].")

# コマンドエラーの共通処理
@bot.event
async def on_command_error(ctx, error):
    if isinstance(error, commands.CommandNotFound):
        return
    if isinstance(error, commands.NoPrivateMessage):
        await ctx.send("このコマンドはサーバー内でのみ使用できます")
        return
    logger.exception("コマンド処理中にエラーが発生しました", exc_info=error)

# ヘルプコマンド
@bot.command()
async def help(ctx):
    help_embed = discord.Embed(title="yomi-KAI", color=0x3399cc)
    help_embed.add_field(name=f"{PREFIX}c", value="発言者と同じボイスチャンネルに接続します。", inline="false")
    help_embed.add_field(name=f"{PREFIX}dc", value="ボイスチャンネルから切断します。", inline="false")
    help_embed.add_field(name=f"{PREFIX}dict", value=f"辞書に関する操作です。詳しくは`{PREFIX}dict help`を参照してください。", inline="false")
    help_embed.add_field(name=f"{PREFIX}sd", value=f"「突然の死」に関する操作です。詳しくは`{PREFIX}sd help`を参照してください。", inline="false")
    help_embed.add_field(name=f"{PREFIX}help", value="このヘルプを表示します。", inline="false")
    await ctx.send(embed=help_embed)
    logger.info("helpを表示")

# ボイスチャンネルに接続
@bot.command()
@commands.guild_only()
async def c(ctx):
    if ctx.author.voice is None:
        await ctx.channel.send(f"{ctx.author.mention}さんはボイスチャンネルに接続していません")
        logger.info(f"{ctx.author}さんはボイスチャンネルに接続していません")
        return

    global connected_channel

    async def connect(ctx):
        view = DropdownView(ctx.guild.id)
        await ctx.send("話者を選んでください", view=view)
        connected_embed = discord.Embed(title="読み上げ開始", color=0x3399cc)
        connected_embed.add_field(name="テキストチャンネル", value=f"{ctx.channel.name}", inline="false")
        connected_embed.add_field(name="ボイスチャンネル", value=f"{ctx.author.voice.channel.name}", inline="false")
        await ctx.send(embed=connected_embed)
        logger.info(f"{ctx.author.voice.channel.name}に接続しました")
        connected_channel[ctx.guild] = ctx.channel

    if ctx.guild.voice_client is not None: # 他のボイスチャンネルに接続していた場合
        await ctx.guild.voice_client.move_to(ctx.author.voice.channel)
        await connect(ctx)
        return

    await ctx.author.voice.channel.connect()
    await connect(ctx)

# ボイスチャンネルから切断
@bot.command()
@commands.guild_only()
async def dc(ctx):
    if ctx.guild.voice_client is None:
        await ctx.channel.send("ボイスチャンネルに接続していません")
        logger.info(f"ボイスチャンネルに接続していません")
        return

    cancel_afk_timer(ctx.guild.id)
    await ctx.guild.voice_client.disconnect()
    await ctx.channel.send("切断しました")
    logger.info(f"切断しました")
    connected_channel.pop(ctx.guild, None)

# 辞書
@bot.command()
@commands.guild_only()
async def dict(ctx, *args):
    if os.path.isfile(f"./dict/{ctx.guild.id}.json"):
        with open(f"./dict/{ctx.guild.id}.json", "r", encoding="UTF-8")as f:
            word = json.load(f)
    else:
        word = {}

    if len(args) == 0:
        await ctx.channel.send(f"コマンドが間違っています。`{PREFIX}dict help`を参照してください")
        logger.info(f"コマンドが間違っています。`{PREFIX}dict help`を参照してください")
        return

    if args[0] == "add" and len(args) == 3:
        word[args[1]] = args[2]
        with open(f"./dict/{ctx.guild.id}.json", "w", encoding="UTF-8")as f:
            f.write(json.dumps(word, indent=2, ensure_ascii=False))
        dict_add_embed = discord.Embed(title="辞書追加", color=0x3399cc)
        dict_add_embed.add_field(name="単語", value=f"{args[1]}", inline="false")
        dict_add_embed.add_field(name="読み", value=f"{args[2]}", inline="false")
        await ctx.send(embed=dict_add_embed)
        logger.info(f"辞書に{args[1]}を{args[2]}として追加しました")
        return

    if args[0] == "del" and len(args) == 2:
        if args[1] not in word:
            await ctx.channel.send(f"`{args[1]}`は辞書に登録されていません")
            logger.info(f"辞書に未登録の単語{args[1]}の削除が試みられました")
            return
        del word[args[1]]
        with open(f"./dict/{ctx.guild.id}.json", "w", encoding="UTF-8")as f:
            f.write(json.dumps(word, indent=2, ensure_ascii=False))
        await ctx.channel.send(f"辞書から`{args[1]}`を削除しました")
        logger.info(f"辞書から{args[1]}を削除しました")
        return

    if args[0] == "list" and len(args) == 1:
        await ctx.channel.send("辞書を表示します")
        logger.info(f"辞書を表示します")
        body = pprint.pformat(word, depth=1)
        # Discordの2000文字制限を超えないように分割して送信
        chunk_size = 1900
        for i in range(0, len(body), chunk_size):
            await ctx.channel.send("```" + body[i:i + chunk_size] + "```")
        return

    if args[0] == "help" and len(args) == 1:
        dict_help_embed = discord.Embed(title="辞書機能ヘルプ", color=0x3399cc)
        dict_help_embed.add_field(name=f"{PREFIX}dict add `word` `yomi`", value="`word`を`yomi`と読むように辞書に追加します。", inline="false")
        dict_help_embed.add_field(name=f"{PREFIX}dict del `word`", value="`word`を辞書から削除します。", inline="false")
        dict_help_embed.add_field(name=f"{PREFIX}dict list", value="現在登録されている辞書を表示します。", inline="false")
        dict_help_embed.add_field(name=f"{PREFIX}dict help", value="このヘルプを表示します。", inline="false")
        await ctx.send(embed=dict_help_embed)
        logger.info("dict helpを表示")
        return

    else:
        await ctx.channel.send(f"コマンドが間違っています。`{PREFIX}dict help`を参照してください")
        logger.info(f"コマンドが間違っています。`{PREFIX}dict help`を参照してください")

# 突然の死
@bot.command()
async def sd(ctx, *args):
    if len(args) == 0:
        await ctx.channel.send(gen_sd_text(SD_MSG))
        return
    if args[0] == "help" and len(args) == 1:
        sd_help_embed = discord.Embed(title="「突然の死」機能ヘルプ", color=0x3399cc)
        sd_help_embed.add_field(name=f"{PREFIX}sd", value=f"{gen_sd_text(SD_MSG)}\nと出力します。", inline="false")
        sd_help_embed.add_field(name=f"{PREFIX}sd `word`", value="＿人人人人＿\n＞　word　＜\n￣Y^Y^Y^Y￣\nのように出力します。複数行には対応していません。", inline="false")
        sd_help_embed.add_field(name=f"{PREFIX}sd help", value="このヘルプを表示します。", inline="false")
        await ctx.send(embed=sd_help_embed)
        logger.info("sd helpを表示")
        return
    if len(args) == 1:
        await ctx.channel.send(gen_sd_text(args[0]))
        return
    else:
        await ctx.channel.send(f"コマンドが間違っています。`{PREFIX}sd help`を参照してください")

def gen_sd_text(msg):
    length = 0
    for c in msg:
        if east_asian_width(c) in 'FWA':
            length += 2
        else:
            length += 1
    sd_text = '＿人'
    for i in range(length//2):
        sd_text += '人'
    sd_text += '人＿\n＞　' + msg + '　＜\n￣Y'
    for i in range(length//2):
        sd_text += '^Y'
    sd_text += '^Y￣'
    return sd_text

# 読み上げ用テキストの整形
def build_read_text(message):
    read_msg = message.content

    # 辞書置換（登録した単語を読みに変換。長い単語を優先してマッチさせる）
    if os.path.isfile(f"./dict/{message.guild.id}.json"):
        with open(f"./dict/{message.guild.id}.json", "r", encoding="UTF-8")as f:
            word = json.load(f)
        if word:
            pattern = re.compile("|".join(re.escape(k) for k in sorted(word, key=len, reverse=True)))
            read_msg = pattern.sub(lambda m: word[m.group(0)], read_msg)

    # URL置換
    read_msg = re.sub(r"https?://.*?\s|https?://.*?$", "URL", read_msg)

    # ネタバレ置換（複数行スポイラーにも対応）
    read_msg = re.sub(r"\|\|.*?\|\|", "ネタバレ", read_msg, flags=re.DOTALL)

    # メンション置換（ユーザー・ロール・チャンネル）
    def replace_user_mention(m):
        member = message.guild.get_member(int(m.group(1)))
        return "アット" + (member.display_name if member else "不明なユーザー")
    read_msg = re.sub(r"<@!?([0-9]+)>", replace_user_mention, read_msg)

    def replace_role_mention(m):
        role = message.guild.get_role(int(m.group(1)))
        return "アット" + (role.name if role else "不明なロール")
    read_msg = re.sub(r"<@&([0-9]+)>", replace_role_mention, read_msg)

    def replace_channel_mention(m):
        channel = message.guild.get_channel(int(m.group(1)))
        return (channel.name if channel else "不明なチャンネル")
    read_msg = re.sub(r"<#([0-9]+)>", replace_channel_mention, read_msg)

    # サーバー絵文字置換（アニメーション絵文字 <a:name:id> も含む）
    read_msg = re.sub(r"<a?:(\w+):[0-9]+>", r"\1", read_msg)

    # *text*置換
    read_msg = re.sub(r"\*(.*?)\*", r"\1", read_msg)

    # _hoge_置換
    read_msg = re.sub(r"_(.*?)_", r"\1", read_msg)

    return read_msg

# メッセージが送られた時
@bot.event
async def on_message(message):
    # コマンドをコマンドとしてトリガーし、読み上げから除外
    if message.content.startswith(PREFIX):
        await bot.process_commands(message)
        return

    # botの発言は無視
    if message.author.bot: return

    # DMなど、サーバー外のメッセージは無視
    if message.guild is None: return

    # 読み上げ
    if message.channel in connected_channel.values() and message.guild.voice_client is not None:
        read_msg = build_read_text(message)

        # 空メッセージ（添付ファイルのみ等）は読み上げをスキップ
        if not read_msg.strip():
            return

        speaker = get_speaker(message.guild.id)
        gen_time = time.time()

        # 音声ファイル作成（ブロッキング処理はスレッドに逃がしてイベントループを止めない）
        try:
            await asyncio.to_thread(synthesize, speaker, read_msg, gen_time)
        except Exception:
            logger.exception("音声合成に失敗しました")
            await message.channel.send("読み上げに失敗しました")
            return

        # 音声読み上げ（再生完了後にファイル削除はafterコールバックで行う）
        wav_path = f"./temp/{gen_time}.wav"
        ffmpeg_path = "./lib/ffmpeg.exe" if os.path.isfile("./lib/ffmpeg.exe") else ("./ffmpeg.exe" if os.path.isfile("./ffmpeg.exe") else "ffmpeg")
        enqueue(message.guild.voice_client, message.guild, discord.FFmpegPCMAudio(wav_path, executable=ffmpeg_path), wav_path)
        logger.info(f"ReadSentence:{read_msg}")

        # AFKタイマーを張り直す
        reset_afk_timer(message.guild)

# AFK自動切断タイマー（ギルドごとに1本だけ保持）
def reset_afk_timer(guild):
    old = afk_tasks.get(guild.id)
    if old is not None:
        old.cancel()
    afk_tasks[guild.id] = asyncio.create_task(afk_timer(guild))

def cancel_afk_timer(guild_id):
    task = afk_tasks.pop(guild_id, None)
    if task is not None:
        task.cancel()

async def afk_timer(guild):
    try:
        await asyncio.sleep(AFK_TIME)
    except asyncio.CancelledError:
        return
    afk_tasks.pop(guild.id, None)
    await do_disconnect(guild, "自動切断しました")

async def do_disconnect(guild, notice):
    if guild.voice_client is None:
        connected_channel.pop(guild, None)
        return
    await guild.voice_client.disconnect()
    channel = connected_channel.pop(guild, None)
    if channel is not None and notice:
        await channel.send(notice)
    logger.info(notice)

# 誰も居なくなると自動切断
@bot.event
async def on_voice_state_update(member, before, after):
    if (
        member.guild.voice_client is not None
        and member.id != bot.user.id
        and member.guild.voice_client.channel is before.channel
        and len(member.guild.voice_client.channel.members) == 1
    ): # ボイスチャンネルに自分だけ参加していたら
        cancel_afk_timer(member.guild.id)
        await do_disconnect(member.guild, "自動切断しました")

try:
    bot.run(DISCORD_TOKEN)
except discord.LoginFailure:
    logger.exception("DISCORD_TOKENが不適切です。")
    sys.exit()
except discord.PrivilegedIntentsRequired:
    logger.exception("Developer PortalでPrivileged Gateway Intentsをすべて有効化してください。")
    sys.exit()
except Exception:
    logger.exception("起動に失敗しました。")
    sys.exit()
